export const events = [
    {
        slug: "react-conf-2025",
        title: "React Conf 2025",
        description: "Join the React community for the premier conference on React, featuring talks from core team members, community leaders, and industry experts.",
        overview: "React Conf 2025 highlights the latest in React development, featuring talks from core team members, community leaders, and industry experts. Learn about the latest features, best practices, and the future of React. Discover new hooks, concurrent features, server components, and real-world applications from the React team and community.",
        image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Moscone Center",
        location: "San Francisco, CA",
        date: "2025-05-15",
        time: "09:00",
        mode: "offline",
        audience: "React developers, frontend engineers, JavaScript enthusiasts",
        agenda: [
            "09:00 AM - 10:00 AM | Keynote: The Future of React",
            "10:15 AM - 11:30 AM | Deep Dives: Server Components, Concurrent Features",
            "11:45 AM - 12:45 PM | Community Talks & Networking",
            "12:45 PM - 01:45 PM | Lunch",
            "01:45 PM - 03:15 PM | Workshops: Advanced React Patterns",
            "03:30 PM - 04:45 PM | Panel: React Ecosystem & Best Practices"
        ],
        organizer: "Meta organizes React Conf to bring together the global React community, showcase innovations, and share knowledge about building modern user interfaces.",
        tags: ["React", "JavaScript", "Frontend", "UI"]
    },
    {
        slug: "nextjs-conf-2025",
        title: "Next.js Conf 2025",
        description: "The official Next.js conference showcasing the latest in full-stack React development. Discover new features, performance optimizations, and real-world applications from the Next.js team and community.",
        overview: "Next.js Conf 2025 showcases the latest in full-stack React development. Discover new features, performance optimizations, and real-world applications from the Next.js team and community. Learn about App Router, Server Actions, streaming, and cutting-edge web development practices.",
        image: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Moscone Center",
        location: "San Francisco, CA",
        date: "2025-06-20",
        time: "10:00",
        mode: "offline",
        audience: "Full-stack developers, Next.js users, React developers",
        agenda: [
            "10:00 AM - 11:00 AM | Keynote: Next.js 15 and Beyond",
            "11:15 AM - 12:30 PM | Deep Dives: App Router, Server Components, Performance",
            "12:45 PM - 01:45 PM | Product Demos & Networking",
            "01:45 PM - 02:45 PM | Lunch",
            "02:45 PM - 04:15 PM | Workshops: Building Production Apps with Next.js",
            "04:30 PM - 05:45 PM | Fireside Chat: The Future of Full-Stack Development"
        ],
        organizer: "Vercel organizes Next.js Conf to connect developers, showcase the latest in Next.js development, and share best practices for building modern web applications.",
        tags: ["Next.js", "React", "Full-Stack", "Web Development"]
    },
    {
        slug: "aws-reinvent-2025",
        title: "AWS re:Invent 2025",
        description: "The world's largest cloud computing conference. Learn from AWS experts, discover new services, attend hands-on workshops, and network with thousands of cloud professionals from around the globe.",
        overview: "AWS re:Invent 2025 is the world's largest cloud computing conference. Learn from AWS experts, discover new services, attend hands-on workshops, and network with thousands of cloud professionals from around the globe. Explore the latest in cloud infrastructure, serverless computing, AI/ML services, and enterprise solutions.",
        image: "https://images.unsplash.com/photo-1551434678-e076c223a692?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Las Vegas Convention Center",
        location: "Las Vegas, NV",
        date: "2025-12-01",
        time: "08:00",
        mode: "offline",
        audience: "Cloud engineers, DevOps, enterprise architects, AWS users",
        agenda: [
            "08:00 AM - 09:30 AM | Keynote: AWS Innovation & Roadmap",
            "09:45 AM - 11:15 AM | Deep Dives: EC2, Lambda, S3, AI Services",
            "11:30 AM - 12:30 PM | Product Demos & Expo",
            "12:30 PM - 01:30 PM | Lunch",
            "01:30 PM - 03:30 PM | Workshops: Building on AWS",
            "03:45 PM - 05:00 PM | Customer Success Stories & Networking"
        ],
        organizer: "Amazon Web Services organizes re:Invent to bring together the global cloud computing community, showcase new services, and share best practices for building scalable cloud applications.",
        tags: ["AWS", "Cloud", "DevOps", "Infrastructure"]
    },
    {
        slug: "mlh-hackathon-2025",
        title: "MLH Major League Hacking",
        description: "Join thousands of developers in this 36-hour hackathon. Build innovative projects, learn new technologies, win prizes, and connect with sponsors and mentors. Open to all skill levels.",
        overview: "MLH Major League Hacking brings together thousands of developers in this 36-hour hackathon. Build innovative projects, learn new technologies, win prizes, and connect with sponsors and mentors. Open to all skill levels, this event features workshops, mentorship, and the opportunity to showcase your creativity and technical skills.",
        image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Virtual & Multiple Locations",
        location: "Virtual & In-Person",
        date: "2025-03-10",
        time: "12:00",
        mode: "hybrid",
        audience: "Students, developers, hackers of all skill levels",
        agenda: [
            "12:00 PM - 01:00 PM | Opening Ceremony & Team Formation",
            "01:00 PM - 02:00 PM | Tech Talks & Workshops",
            "02:00 PM - 08:00 PM | Hacking Begins - Build Your Project",
            "08:00 PM - 09:00 PM | Dinner Break",
            "09:00 PM - 02:00 AM | Late Night Hacking & Mentorship",
            "02:00 AM - 08:00 AM | Overnight Hacking Session",
            "08:00 AM - 09:00 AM | Breakfast",
            "09:00 AM - 12:00 PM | Final Hacking & Project Polish",
            "12:00 PM - 02:00 PM | Project Submissions & Judging",
            "02:00 PM - 03:00 PM | Awards Ceremony"
        ],
        organizer: "Major League Hacking organizes hackathons worldwide to help students learn new technologies, build projects, and connect with the developer community.",
        tags: ["Hackathon", "Programming", "Innovation", "Learning"]
    },
    {
        slug: "jsconf-2025",
        title: "JSConf US 2025",
        description: "A community-driven JavaScript conference featuring cutting-edge talks on web development, Node.js, frameworks, and the JavaScript ecosystem. Experience the best of the JS community.",
        overview: "JSConf US 2025 is a community-driven JavaScript conference featuring cutting-edge talks on web development, Node.js, frameworks, and the JavaScript ecosystem. Experience the best of the JS community with talks from renowned speakers, hands-on workshops, and networking opportunities.",
        image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Austin Convention Center",
        location: "Austin, TX",
        date: "2025-08-25",
        time: "09:30",
        mode: "offline",
        audience: "JavaScript developers, Node.js developers, web developers",
        agenda: [
            "09:30 AM - 10:30 AM | Keynote: The State of JavaScript",
            "10:45 AM - 12:00 PM | Talks: Modern JavaScript, Frameworks, Tools",
            "12:15 PM - 01:15 PM | Networking & Sponsor Expo",
            "01:15 PM - 02:15 PM | Lunch",
            "02:15 PM - 04:00 PM | Workshops: Advanced JavaScript Patterns",
            "04:15 PM - 05:30 PM | Panel: The Future of JavaScript"
        ],
        organizer: "JSConf organizes community-driven JavaScript conferences to bring together developers, share knowledge, and celebrate the JavaScript ecosystem.",
        tags: ["JavaScript", "Node.js", "Web Development", "Community"]
    },
    {
        slug: "devops-world-2025",
        title: "DevOps World 2025",
        description: "The premier DevOps and cloud-native conference. Learn about CI/CD, Kubernetes, microservices, infrastructure as code, and modern software delivery practices from industry leaders.",
        overview: "DevOps World 2025 is the premier DevOps and cloud-native conference. Learn about CI/CD, Kubernetes, microservices, infrastructure as code, and modern software delivery practices from industry leaders. Discover tools, techniques, and strategies for building and deploying applications at scale.",
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Orange County Convention Center",
        location: "Orlando, FL",
        date: "2025-09-15",
        time: "08:30",
        mode: "offline",
        audience: "DevOps engineers, SREs, cloud architects, platform engineers",
        agenda: [
            "08:30 AM - 09:30 AM | Keynote: The Future of DevOps",
            "09:45 AM - 11:15 AM | Deep Dives: Kubernetes, CI/CD, Infrastructure",
            "11:30 AM - 12:30 PM | Product Demos & Expo",
            "12:30 PM - 01:30 PM | Lunch",
            "01:30 PM - 03:30 PM | Workshops: Kubernetes, Terraform, GitOps",
            "03:45 PM - 05:00 PM | Fireside Chat: Scaling DevOps Practices"
        ],
        organizer: "DevOps World organizes conferences to bring together DevOps professionals, share best practices, and showcase the latest tools and technologies in modern software delivery.",
        tags: ["DevOps", "Kubernetes", "CI/CD", "Cloud-Native"]
    },
    {
        slug: "ai-summit-2025",
        title: "AI Summit 2025",
        description: "Explore the cutting edge of artificial intelligence and machine learning. Featuring keynote speakers from leading AI companies, hands-on workshops, and discussions on the future of AI in business and society.",
        overview: "AI Summit 2025 explores the cutting edge of artificial intelligence and machine learning. Featuring keynote speakers from leading AI companies, hands-on workshops, and discussions on the future of AI in business and society. Learn about LLMs, generative AI, computer vision, and ethical AI practices.",
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Jacob K. Javits Convention Center",
        location: "New York, NY",
        date: "2025-04-22",
        time: "09:00",
        mode: "offline",
        audience: "AI researchers, data scientists, ML engineers, business leaders",
        agenda: [
            "09:00 AM - 10:00 AM | Keynote: The AI Revolution",
            "10:15 AM - 11:45 AM | Deep Dives: LLMs, Generative AI, Computer Vision",
            "12:00 PM - 01:00 PM | Product Demos & Networking",
            "01:00 PM - 02:00 PM | Lunch",
            "02:00 PM - 04:00 PM | Workshops: Building AI Applications",
            "04:15 PM - 05:30 PM | Panel: Ethics and the Future of AI"
        ],
        organizer: "AI Summit organizes conferences to bring together AI researchers, practitioners, and business leaders to explore the latest developments in artificial intelligence and machine learning.",
        tags: ["AI", "Machine Learning", "Data Science", "Innovation"]
    },
    {
        slug: "google-io-2025",
        title: "Google I/O 2025",
        description: "Google's annual developer conference showcasing the latest in Android, Chrome, Firebase, TensorFlow, and Google Cloud. Get hands-on experience with new APIs, tools, and technologies.",
        overview: "Google I/O 2025 is Google's annual developer conference showcasing the latest in Android, Chrome, Firebase, TensorFlow, and Google Cloud. Get hands-on experience with new APIs, tools, and technologies. Learn from Google engineers, attend workshops, and discover what's next in Google's developer ecosystem.",
        image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Shoreline Amphitheatre",
        location: "Mountain View, CA",
        date: "2025-05-07",
        time: "10:00",
        mode: "hybrid",
        audience: "Android developers, web developers, Google Cloud users, AI researchers",
        agenda: [
            "10:00 AM - 11:30 AM | Keynote: Google's Latest Innovations",
            "11:45 AM - 01:00 PM | Deep Dives: Android, Chrome, Firebase, TensorFlow",
            "01:00 PM - 02:00 PM | Lunch",
            "02:00 PM - 03:30 PM | Product Demos & Hands-On Labs",
            "03:45 PM - 05:15 PM | Workshops: Building with Google Technologies",
            "05:30 PM - 06:45 PM | Fireside Chat: The Future of Google's Platform"
        ],
        organizer: "Google organizes I/O to connect developers with the latest in Google's technology stack, showcase new products and APIs, and share best practices for building modern applications.",
        tags: ["Google", "Android", "Chrome", "Cloud"]
    },
    {
        slug: "wwdc-2025",
        title: "Apple WWDC 2025",
        description: "Apple's Worldwide Developers Conference. Discover the latest innovations in iOS, macOS, watchOS, and tvOS. Learn from Apple engineers and connect with the global developer community.",
        overview: "Apple WWDC 2025 is Apple's Worldwide Developers Conference. Discover the latest innovations in iOS, macOS, watchOS, and tvOS. Learn from Apple engineers and connect with the global developer community. Explore new frameworks, APIs, design guidelines, and development tools.",
        image: "https://images.unsplash.com/photo-1511578314322-379afb476865?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Apple Park",
        location: "Cupertino, CA",
        date: "2025-06-09",
        time: "10:00",
        mode: "hybrid",
        audience: "iOS developers, macOS developers, Apple platform developers",
        agenda: [
            "10:00 AM - 11:30 AM | Keynote: Apple's Latest Platforms & Technologies",
            "11:45 AM - 01:00 PM | Platform State of the Union: iOS, macOS, watchOS, tvOS",
            "01:00 PM - 02:00 PM | Lunch",
            "02:00 PM - 03:30 PM | Sessions: New Frameworks & APIs",
            "03:45 PM - 05:15 PM | Labs: One-on-One with Apple Engineers",
            "05:30 PM - 06:45 PM | Design & Development Best Practices"
        ],
        organizer: "Apple organizes WWDC to bring together the global Apple developer community, showcase new platforms and technologies, and provide hands-on learning opportunities with Apple engineers.",
        tags: ["Apple", "iOS", "macOS", "Swift"]
    },
    {
        slug: "dockercon-2025",
        title: "DockerCon 2025",
        description: "The containerization and microservices conference. Learn about Docker, Kubernetes, container orchestration, and modern application deployment strategies from industry experts.",
        overview: "DockerCon 2025 is the containerization and microservices conference. Learn about Docker, Kubernetes, container orchestration, and modern application deployment strategies from industry experts. Discover best practices for building, shipping, and running distributed applications.",
        image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "San Diego Convention Center",
        location: "San Diego, CA",
        date: "2025-07-14",
        time: "08:00",
        mode: "offline",
        audience: "DevOps engineers, containerization experts, platform engineers",
        agenda: [
            "08:00 AM - 09:00 AM | Keynote: The Future of Containerization",
            "09:15 AM - 10:45 AM | Deep Dives: Docker, Kubernetes, Container Security",
            "11:00 AM - 12:00 PM | Product Demos & Expo",
            "12:00 PM - 01:00 PM | Lunch",
            "01:00 PM - 03:00 PM | Workshops: Docker & Kubernetes Best Practices",
            "03:15 PM - 04:30 PM | Panel: Container Orchestration Strategies"
        ],
        organizer: "Docker organizes DockerCon to bring together the containerization community, showcase new features and tools, and share best practices for building and deploying containerized applications.",
        tags: ["Docker", "Kubernetes", "Containers", "Microservices"]
    },
    {
        slug: "cybersecurity-summit-2025",
        title: "Cybersecurity Summit 2025",
        description: "A comprehensive security conference covering threat intelligence, zero-trust architecture, cloud security, incident response, and the latest in cybersecurity best practices and technologies.",
        overview: "Cybersecurity Summit 2025 is a comprehensive security conference covering threat intelligence, zero-trust architecture, cloud security, incident response, and the latest in cybersecurity best practices and technologies. Learn from security experts and discover strategies for protecting modern digital infrastructure.",
        image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Walter E. Washington Convention Center",
        location: "Washington, DC",
        date: "2025-10-08",
        time: "09:00",
        mode: "offline",
        audience: "Security professionals, CISOs, security engineers, compliance officers",
        agenda: [
            "09:00 AM - 10:00 AM | Keynote: The Evolving Threat Landscape",
            "10:15 AM - 11:45 AM | Deep Dives: Zero-Trust, Cloud Security, Threat Intelligence",
            "12:00 PM - 01:00 PM | Product Demos & Networking",
            "01:00 PM - 02:00 PM | Lunch",
            "02:00 PM - 04:00 PM | Workshops: Security Best Practices & Incident Response",
            "04:15 PM - 05:30 PM | Panel: The Future of Cybersecurity"
        ],
        organizer: "Cybersecurity Summit organizes conferences to bring together security professionals, share threat intelligence, and showcase the latest tools and strategies for protecting digital assets.",
        tags: ["Cybersecurity", "Security", "Zero-Trust", "Compliance"]
    },
    {
        slug: "ux-design-week-2025",
        title: "UX Design Week 2025",
        description: "A gathering of UX designers, researchers, and product managers. Explore user-centered design, accessibility, design systems, and the intersection of design and technology.",
        overview: "UX Design Week 2025 brings together UX designers, researchers, and product managers. Explore user-centered design, accessibility, design systems, and the intersection of design and technology. Learn about design thinking, user research methods, and creating inclusive digital experiences.",
        image: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Oregon Convention Center",
        location: "Portland, OR",
        date: "2025-07-28",
        time: "09:30",
        mode: "offline",
        audience: "UX designers, UI designers, product managers, design researchers",
        agenda: [
            "09:30 AM - 10:30 AM | Keynote: The Future of UX Design",
            "10:45 AM - 12:15 PM | Deep Dives: Design Systems, Accessibility, User Research",
            "12:30 PM - 01:30 PM | Networking & Sponsor Expo",
            "01:30 PM - 02:30 PM | Lunch",
            "02:30 PM - 04:30 PM | Workshops: Design Thinking & Prototyping",
            "04:45 PM - 06:00 PM | Panel: Design & Technology Collaboration"
        ],
        organizer: "UX Design Week organizes conferences to bring together design professionals, share best practices, and explore the latest trends in user experience design and research.",
        tags: ["UX", "Design", "User Research", "Accessibility"]
    },
    {
        slug: "mobile-dev-summit-2025",
        title: "Mobile Dev Summit 2025",
        description: "The premier mobile development conference covering iOS, Android, React Native, Flutter, and cross-platform development. Learn from mobile experts and discover the latest tools and frameworks.",
        overview: "Mobile Dev Summit 2025 is the premier mobile development conference covering iOS, Android, React Native, Flutter, and cross-platform development. Learn from mobile experts and discover the latest tools and frameworks. Explore native and cross-platform strategies, performance optimization, and mobile app architecture.",
        image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Washington State Convention Center",
        location: "Seattle, WA",
        date: "2025-11-12",
        time: "08:30",
        mode: "offline",
        audience: "Mobile developers, iOS developers, Android developers, cross-platform developers",
        agenda: [
            "08:30 AM - 09:30 AM | Keynote: The Future of Mobile Development",
            "09:45 AM - 11:15 AM | Deep Dives: iOS, Android, React Native, Flutter",
            "11:30 AM - 12:30 PM | Product Demos & Networking",
            "12:30 PM - 01:30 PM | Lunch",
            "01:30 PM - 03:30 PM | Workshops: Building Native & Cross-Platform Apps",
            "03:45 PM - 05:00 PM | Panel: Native vs Cross-Platform Strategies"
        ],
        organizer: "Mobile Dev Summit organizes conferences to bring together mobile developers, showcase the latest frameworks and tools, and share best practices for building high-quality mobile applications.",
        tags: ["Mobile", "iOS", "Android", "React Native"]
    },
    {
        slug: "graphql-conf-2025",
        title: "GraphQL Conf 2025",
        description: "The global GraphQL conference bringing together developers, architects, and companies building with GraphQL. Learn about schema design, performance optimization, and real-world implementations.",
        overview: "GraphQL Conf 2025 is the global GraphQL conference bringing together developers, architects, and companies building with GraphQL. Learn about schema design, performance optimization, and real-world implementations. Explore GraphQL best practices, federation, subscriptions, and building modern APIs.",
        image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Berlin Congress Center",
        location: "Berlin, Germany",
        date: "2025-06-05",
        time: "09:00",
        mode: "offline",
        audience: "GraphQL developers, API architects, backend engineers",
        agenda: [
            "09:00 AM - 10:00 AM | Keynote: The GraphQL Ecosystem",
            "10:15 AM - 11:45 AM | Deep Dives: Schema Design, Federation, Performance",
            "12:00 PM - 01:00 PM | Networking & Sponsor Expo",
            "01:00 PM - 02:00 PM | Lunch",
            "02:00 PM - 04:00 PM | Workshops: Building GraphQL APIs",
            "04:15 PM - 05:30 PM | Panel: GraphQL in Production"
        ],
        organizer: "GraphQL Foundation organizes GraphQL Conf to bring together the global GraphQL community, share knowledge, and showcase the latest developments in GraphQL technology.",
        tags: ["GraphQL", "API", "Backend", "Data"]
    },
    {
        slug: "techcrunch-disrupt-2025",
        title: "TechCrunch Disrupt 2025",
        description: "Where startups meet investors, innovators, and industry leaders. Featuring the Startup Battlefield competition, expert panels, networking opportunities, and the latest in tech innovation.",
        overview: "TechCrunch Disrupt 2025 is where startups meet investors, innovators, and industry leaders. Featuring the Startup Battlefield competition, expert panels, networking opportunities, and the latest in tech innovation. Discover emerging technologies, connect with investors, and learn from successful entrepreneurs.",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=2340",
        venue: "Moscone Center",
        location: "San Francisco, CA",
        date: "2025-09-18",
        time: "08:00",
        mode: "offline",
        audience: "Startup founders, investors, entrepreneurs, tech industry leaders",
        agenda: [
            "08:00 AM - 09:00 AM | Opening Keynote: The Startup Landscape",
            "09:15 AM - 10:45 AM | Startup Battlefield Competition",
            "11:00 AM - 12:00 PM | Expert Panels & Fireside Chats",
            "12:00 PM - 01:00 PM | Lunch & Networking",
            "01:00 PM - 03:00 PM | Startup Demos & Investor Meetings",
            "03:15 PM - 04:30 PM | Closing Keynote: The Future of Tech"
        ],
        organizer: "TechCrunch organizes Disrupt to bring together startups, investors, and industry leaders, showcase innovation, and provide opportunities for networking and investment.",
        tags: ["Startups", "Innovation", "Entrepreneurship", "Investment"]
    }
];
